In [27]:
import pandas as pd
import numpy as np

In [28]:
df = pd.read_csv("/kaggle/input/goldman-sachs-all-time-stock-data/goldmansachs.csv");
display(df)

,date,open,high,low,close,adj_close,volume
0,1999-05-04,48.696575,70.375000,77.250000,70.000000,76.000000,22320900
1,1999-05-05,47.831593,69.125000,69.875000,66.250000,69.875000,7565700
2,1999-05-06,47.009914,67.937500,69.375000,67.062500,68.000000,2905700
3,1999-05-07,51.291405,74.125000,74.875000,66.750000,67.937500,4862300
4,1999-05-10,48.912811,70.687500,73.500000,70.250000,73.375000,2589400
...,...,...,...,...,...,...,...
6704,2025-12-26,907.039978,907.039978,913.320007,905.309998,911.000000,995300
6705,2025-12-29,892.179993,892.179993,906.479980,891.559998,906.450012,1578000
6706,2025-12-30,884.419983,884.419983,895.020020,881.179993,894.739990,1833300
6707,2025-12-31,879.000000,879.000000,886.000000,876.789978,884.099976,1221500
6708,2026-01-02,914.340027,914.340027,914.440002,880.750000,884.000000,2816200

In [29]:
df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d')
X = df[['date', 'high', 'low', 'adj_close', 'volume']].copy()

# Y target (MULTI-OUTPUT)
Y = df[['open', 'close']].copy()

#Converting the Date Month and Year...
X['year'] = X['date'].dt.year
X['month'] = X['date'].dt.month
X['day'] = X['date'].dt.day
X.drop(columns='date', inplace=True)

In [33]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,Y, test_size=0.2, random_state=42
)

In [35]:
print("X_train shape:", X_train.shape)
display(X_train.head())

print("X_test shape:", X_test.shape)
display(X_test.head())

print("y_train shape:", y_train.shape)
display(y_train.head())

print("y_test shape:", y_test.shape)
display(y_test.head())

X_train shape: (5367, 7)

            high         low   adj_close   volume  year  month  day
6547  603.809998  607.710022  593.299988  2765800  2025      5   13
6032  343.959991  345.059998  341.989990  1966300  2023      4   24
6670  787.580017  798.200012  794.000000  1572500  2025     11    6
6212  381.959991  383.049988  381.350006  1547300  2024      1   10
3871  185.289993  186.949997  186.000000  1826100  2014      9   22

X_test shape: (1342, 7)

            high         low   adj_close   volume  year  month  day
1188  102.279999  102.489998   99.419998  4096200  2004      1   26
5916  348.869995  350.670013  347.500000  2515600  2022     11    3
247    97.062500   97.875000   88.625000  1341500  2000      4   25
5960  353.000000  356.500000  351.880005  1989000  2023      1    9
2836  149.250000  152.000000  151.720001  7734400  2010      8   11

y_train shape: (5367, 2)

            open       close
6547  594.667969  593.059998
6032  321.282318  341.529999
6670  783.694824  777.000000
6212  365.467682  378.529999
3871  148.563766  185.100006

y_test shape: (1342, 2)

            open       close
1188   73.215675   99.349998
5916  321.443787  342.589996
247    67.618080   87.500000
5960  327.382111  349.500000
2836  113.189537  148.910004

In [36]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', RandomForestRegressor(n_estimators=200))
])

pipeline.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('model', RandomForestRegressor(n_estimators=200))])

In [37]:
y_pred = pipeline.predict(X_test)

In [38]:
from sklearn.metrics import mean_absolute_error, r2_score

print("MAE:", mean_absolute_error(y_test, y_pred))
print("R2:", r2_score(y_test, y_pred))

MAE: 0.8554352885102721
R2: 0.999784497850257

In [41]:
new_X = [[
    355.50,     # high
    348.20,     # low
    352.10,     # adj_close
    1450000,    # volume
    2024,       # year
    2,          # month
    10          # day
]]

# Suppose these are your training column names
columns = ['high', 'low', 'adj_close', 'volume', 'year', 'month', 'day']

# Convert your new_X to a DataFrame
new_X_df = pd.DataFrame(new_X, columns=columns)


prediction = pipeline.predict(new_X_df)

pred_open = prediction[0][0]
pred_close = prediction[0][1]

print("Predicted Opening Price:", round(pred_open, 2))
print("Predicted Closing Price:", round(pred_close, 2))

Predicted Opening Price: 330.25
Predicted Closing Price: 350.04